export const SCENES = {
  scene1: {
    id: 'scene1',
    title: 'Escena 1',
    subtitle: 'El salón de clases',
    background: 'assets/scenes/escena1.png',
    dialogues: [
      { speaker: 'PROFESORA BÚHO', text: 'Conejitos.' },
      { speaker: 'CONEJITOS', text: '¡Presentes!' },
      { speaker: 'PROFESORA BÚHO', text: 'Ardillas.' },
      { speaker: 'ARDILLAS', text: '¡Presentes!' },
      { speaker: 'PROFESORA BÚHO', text: 'Panditas.' },
      { speaker: 'NENNIS', text: '¡Presente!' },
      { speaker: 'NENNIS', text: 'Uno… dos… tres…' },
      { speaker: 'NENNIS', text: 'Profesora… creo que faltan pandas.' },
      { speaker: 'PROFESORA BÚHO', text: 'No falta ninguno, Nennis.' },
      { speaker: 'NENNIS', text: '¿Ninguno?' },
      { speaker: 'NENNIS', text: 'Entonces esto es mucho más grave de lo que pensaba.' },
      { speaker: 'NENNIS', text: 'Tenemos un misterio.' },
    ],
    next: 'scene2',
  },

  scene2: {
    id: 'scene2',
    title: 'Escena 2',
    subtitle: 'La oficina improvisada de Nennis',
    background: 'assets/scenes/escena2.png',
    dialogues: [
      { speaker: 'NENNIS', text: 'Caso número dos: ¿por qué hay tan pocos pandas en la escuela?' },
      { speaker: 'NENNIS', text: 'Primera teoría: el autobús se olvida de nosotros.' },
      { speaker: 'NENNIS', text: 'Segunda teoría: demasiado bambú. Bastante probable.' },
      { speaker: 'NENNIS', text: 'Tercera teoría: existe una escuela secreta de pandas.' },
      { speaker: 'NENNIS', text: 'Sí… esa suena especialmente misteriosa.' },
      { speaker: 'PROFESORA BÚHO', text: 'Quizás quieras empezar por algo un poco más comprobable.' },
      { speaker: 'NENNIS', text: '¿Una pista?' },
      { speaker: 'PROFESORA BÚHO', text: 'Una dirección.' },
      { speaker: 'NENNIS', text: '¡Aún mejor!' },
    ],
    next: 'scene3',
  },

  scene3: {
    id: 'scene3',
    title: 'Escena 3',
    subtitle: 'El pasillo de los retratos',
    background: 'assets/scenes/escena3.png',
    dialogues: [
      { speaker: 'NENNIS', text: 'Muchos conejos… muchos zorros…' },
      { speaker: 'NENNIS', text: 'Panda dormido. Sospechoso.' },
      { speaker: 'NENNIS', text: 'Panda comiendo. Muy sospechoso.' },
      { speaker: 'NENNIS', text: '¡Oh! Una detective panda.' },
      { speaker: 'NENNIS', text: 'Lupa grande, postura seria… claramente sabía lo que hacía.' },
      { speaker: 'NENNIS', text: '¿Y esa flecha?' },
    ],
    next: 'scene4_intro',
  },

  scene4_intro: {
    id: 'scene4_intro',
    title: 'Escena 4',
    subtitle: 'El Archivo de los Ciclos',
    background: 'assets/scenes/escena4.png',
    dialogues: [
      { speaker: 'SISTEMA', text: 'Para consultar los archivos debes reconstruir el calendario.' },
      { speaker: 'NENNIS', text: 'Perfecto. Los calendarios jamás han derrotado a una detective.' },
      { speaker: 'NENNIS', text: 'Creo.' },
    ],
    next: 'minigame_calendar',
  },

  scene4_end: {
    id: 'scene4_end',
    title: null,
    background: 'assets/scenes/escena4.png',
    dialogues: [
      { speaker: 'NENNIS', text: '¡Ajá! Hay una especie con una sola temporada marcada.' },
      { speaker: 'NENNIS', text: 'Los pandas gigantes tienen una temporada reproductiva una vez al año… 1' },
      { speaker: 'NENNIS', text: '¿Temporada oficial de panditas? Interesante.' },
      { speaker: 'NENNIS', text: 'Y esta llave… definitivamente abre algo.' },
    ],
    next: 'scene5',
  },

  scene5: {
    id: 'scene5',
    title: 'Escena 5',
    subtitle: 'El Jardín de los Relojes',
    background: 'assets/scenes/escena5.png',
    dialogues: [
      { speaker: 'NENNIS', text: 'Una llave con forma de reloj necesita una cerradura con forma de reloj.' },
      { speaker: 'NENNIS', text: 'Eso reduce mis sospechosos a…' },
      { speaker: 'NENNIS', text: 'Muchísimos relojes.' },
      { speaker: 'NENNIS', text: 'No.' },
      { speaker: 'NENNIS', text: 'Tampoco.' },
      { speaker: 'NENNIS', text: 'Definitivamente el bambú no era una cerradura.' },
      { speaker: 'NENNIS', text: '¡Aquí estás!' },
    ],
    next: 'scene6_intro',
  },

  scene6_intro: {
    id: 'scene6_intro',
    title: 'Escena 6',
    subtitle: 'El Invernadero del Tiempo',
    background: 'assets/scenes/escena6.png',
    dialogues: [
      { speaker: 'SISTEMA', text: 'Encontrar la temporada no es suficiente. Descubre cuánto dura la oportunidad.' },
      { speaker: 'NENNIS', text: '¿Cuánto dura? Entonces el tiempo importa.' },
    ],
    next: 'minigame_precision',
  },

  scene6_end: {
    id: 'scene6_end',
    title: null,
    background: 'assets/scenes/escena6.png',
    dialogues: [
      { speaker: 'NENNIS', text: '¡Justo ahí!' },
      { speaker: 'NENNIS', text: 'Dentro de esa temporada, las pandas gigantes solo tienen unos pocos días fértiles… 8' },
      { speaker: 'NENNIS', text: 'Entonces no solamente ocurre una vez al año.' },
      { speaker: 'NENNIS', text: 'Además hay que coincidir con unos poquitos días.' },
      { speaker: 'NENNIS', text: '¿Y esta fotografía?' },
    ],
    next: 'scene7',
  },

  scene7: {
    id: 'scene7',
    title: 'Escena 7',
    subtitle: 'El comedor de la escuela',
    background: 'assets/scenes/escena7.png',
    dialogues: [
      { speaker: 'NENNIS', text: 'Archivo de las Familias… debe estar cerca.' },
      { speaker: 'NENNIS', text: 'Concentración, Nennis. Nada puede distraerte.' },
      { speaker: 'NENNIS', text: '…' },
      { speaker: 'NENNIS', text: '¿Eso es bambú fresco?' },
      { speaker: 'NENNIS', text: 'Una detective necesita energía.' },
      { speaker: 'NENNIS', text: 'Espera. Esa fotografía… yo ya la vi.' },
      { speaker: 'NENNIS', text: '¡Coincide!' },
      { speaker: 'NENNIS', text: '¿Y este botón estaba aquí todo el tiempo?' },
    ],
    next: 'scene8_intro',
  },

  scene8_intro: {
    id: 'scene8_intro',
    title: 'Escena 8',
    subtitle: 'El Archivo de las Familias',
    background: 'assets/scenes/escena8.png',
    dialogues: [
      { speaker: 'NENNIS', text: 'Familias, especies y cantidades… esto sí parece trabajo de detective.' },
    ],
    next: 'minigame_logic',
  },

  scene8_end: {
    id: 'scene8_end',
    title: null,
    background: 'assets/scenes/escena8.png',
    dialogues: [
      { speaker: 'NENNIS', text: 'La familia panda está asociada con uno de los grupos más pequeños.' },
      { speaker: 'NENNIS', text: 'Creo que ya lo tengo.' },
      { speaker: 'NENNIS', text: 'Los pandas gigantes suelen tener pocas crías en cada gestación… 0' },
      { speaker: 'NENNIS', text: 'Una temporada. Poquitos días. Poquitos bebés panda.' },
      { speaker: 'NENNIS', text: '¡Creo que resolví el caso!' },
    ],
    next: 'scene9',
  },

  scene9: {
    id: 'scene9',
    title: 'Escena 9',
    subtitle: 'La carrera de regreso',
    background: 'assets/scenes/escena9.png',
    dialogues: [
      { speaker: 'NENNIS', text: '¡Permiso! ¡Detective trabajando!' },
      { speaker: 'NENNIS', text: 'Calendario: una temporada.' },
      { speaker: 'NENNIS', text: 'Reloj: pocos días.' },
      { speaker: 'NENNIS', text: 'Familias: pocas crías.' },
      { speaker: 'NENNIS', text: 'Eso significa que…' },
      { speaker: 'NENNIS', text: '¡Woooaaah!' },
      { speaker: 'NENNIS', text: '…' },
      { speaker: 'NENNIS', text: 'Entrada completamente planeada.' },
    ],
    next: 'scene10',
  },

  scene10: {
    id: 'scene10',
    title: 'Escena 10',
    subtitle: 'La resolución frente al tablero',
    background: 'assets/scenes/escena1.png',
    dialogues: [
      { speaker: 'NENNIS', text: '¡He descubierto la verdad!' },
      { speaker: 'NENNIS', text: '¿El autobús pierde a los pandas? No.' },
      { speaker: 'NENNIS', text: '¿Nos quedamos comiendo bambú? A veces. Pero no explica el misterio.' },
      { speaker: 'NENNIS', text: '¿Existe una escuela secreta de pandas?' },
      { speaker: 'NENNIS', text: 'No encontré pruebas suficientes. El caso sigue abierto.' },
      { speaker: 'PROFESORA BÚHO', text: 'Nennis…' },
      { speaker: 'NENNIS', text: 'Continuemos.' },
      { speaker: 'NENNIS', text: 'Primera pista: los pandas tienen una temporada reproductiva una vez al año.' },
      { speaker: 'NENNIS', text: 'Segunda pista: dentro de esa temporada, la ventana fértil dura muy pocos días.' },
      { speaker: 'NENNIS', text: 'Tercera pista: además, suelen tener pocas crías.' },
      { speaker: 'NENNIS', text: 'Por eso nacen menos panditas que en especies que tienen más oportunidades y camadas mayores.' },
      { speaker: 'PANDITA 2', text: '¿Entonces no faltamos?' },
      { speaker: 'NENNIS', text: 'Exactamente.' },
      { speaker: 'NENNIS', text: '¡Somos edición limitada!' },
      { speaker: 'PROFESORA BÚHO', text: 'Esa es… una forma de decirlo.' },
    ],
    next: 'scene11_intro',
  },

  scene11_intro: {
    id: 'scene11_intro',
    title: 'Escena 11',
    subtitle: 'El código secreto',
    background: 'assets/scenes/escena11.png',
    dialogues: [
      { speaker: 'NENNIS', text: 'Un momento.' },
      { speaker: 'NENNIS', text: 'Mis pistas tienen números.' },
      { speaker: 'PROFESORA BÚHO', text: '¿Y qué hace una detective cuando encuentra algo que no comprende?' },
      { speaker: 'NENNIS', text: 'Lo mira fijamente hasta que se vuelve comprensible.' },
      { speaker: 'PROFESORA BÚHO', text: 'También puedes usar tu libreta.' },
      { speaker: 'NENNIS', text: 'Cierto.' },
    ],
    next: 'minigame_code',
  },

  scene11_end: {
    id: 'scene11_end',
    title: null,
    background: 'assets/scenes/escena11.png',
    dialogues: [
      { speaker: 'NENNIS', text: '¡Uno, ocho, cero!' },
      { speaker: 'NENNIS', text: '¡Certificado oficial de Detective Ayudante!' },
      { speaker: 'NENNIS', text: 'Y… ¡mi bambú!' },
      { speaker: 'PROFESORA BÚHO', text: 'Tú lo guardaste ahí esta mañana.' },
      { speaker: 'NENNIS', text: '…' },
      { speaker: 'NENNIS', text: 'Profesora.' },
      { speaker: 'PROFESORA BÚHO', text: '¿Sí?' },
      { speaker: 'NENNIS', text: 'Creo que tenemos un nuevo caso.' },
    ],
    next: 'ending',
  },
};
